### ISSUE TITLE
replace classes with Hooks

### ISSUE THREAD

**Issue by theDavidBarton** [theDavidBarton/trending-movies-react-app#73]
it is planned for all my React.js projects.

**Comment by theDavidBarton** [comment]
**Roadmap:**

- [x] 404.jsx
- [x] app.jsx
- [x] cookieBar.jsx
- [x] footer.jsx
- [x] header.jsx (requires `useEffect!`)
- [x] homepageWrapper.jsx (requires `useEffect!`)
- [x] langSelector.jsx
- [x] movieDetails.jsx (requires `useEffect!`)
- [x] movieDetailsWrapper.jsx
- [x] searchForm.jsx (requires `useEffect!`)
- [x] trendingMovie.jsx
- [x] trendingMovieList.jsx
- [x] trendingMovieSkeletonLoading.jsx
